<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGFdIgtz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGFdIgtz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGFdIgtz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGFdIgtz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGFdIgtz\App_KernelDevDebugContainer([
    'container.build_hash' => 'GFdIgtz',
    'container.build_id' => 'a963f1fd',
    'container.build_time' => 1738664540,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGFdIgtz');
